### ISSUE TITLE
Null case not matched

### ISSUE THREAD

**Issue by kolakode** [plewyllie/yangre-gui#7]
I entered the following pattern (with the quotes) and no test string into https://yangcatalog.org/yangre/

`"([a-zA-Z])?"`

and got this error:

```Pattern 1 YANGRE does not match
yangre error: Value " " does not satisfy the constraint
"([a-zA-Z])?" (range, length, or pattern).
```

The match is clearly optional, so I would think a null input should match.

**Comment by plewyllie** [comment]
Hi, thanks for letting me know! I actually tracked it down to the actual validator in the back-end and submitted a pull request: https://github.com/CESNET/libyang/pull/385

I have fixed it on my end, and it will be put in production soon. I'll close the ticket as soon as it's working in prod.

Cheers,
Pieter
